version: '3.0'

services:
  main:
    container_name: app
    image: react2022/hola:1.0.0
    env_file:
      - .docker.env
    ports:
      - 8080:5000
    command: node index.js
    depends_on:
      - redis
    restart: always
  redis-server:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

volumes:
  cache: